// ****
// *
// * #defines for configuring the radiation model
// *
// * (c) Dr. Stephen J. Bradshaw
// *
// * Source code generated by HYDRAD_GUI on 24-11-2015 18:43:32
// *
// ****

// **** Physics ****
// Radiation //
// End of Radiation //
// Collisions //
#define MINIMUM_COLLISIONAL_COUPLING_TIME_SCALE 0.01
// End of Collisions //
// **** End of Physics ****

// **** Solver ****
#define MAX_OPTICALLY_THIN_DENSITY 12.0
#define SAFETY_ATOMIC 1.0
#define CUTOFF_ION_FRACTION 1E-5
#define EPSILON_D 0.1
#define EPSILON_R 1.8649415311920072
// **** End of Solver ****
