// ****
// *
// * #defines for configuring the radiation model
// *
// * (c) Dr. Stephen J. Bradshaw
// *
// * Source code generated by HYDRAD_GUI on 03-11-2017 15:31:12
// *
// ****

// **** Physics ****
// Radiation //
#define USE_POWER_LAW_RADIATIVE_LOSSES
// End of Radiation //
// Collisions //
#include "../../HYDRAD/source/collisions.h"
// End of Collisions //
// **** End of Physics ****

// **** Solver ****
#define MAX_OPTICALLY_THIN_DENSITY 12.0
#define SAFETY_ATOMIC 1.0
#define CUTOFF_ION_FRACTION 1E-6
#define EPSILON_D 0.1
#define EPSILON_R 1.8649415311920072
// **** End of Solver ****
