// ****
// *
// * #defines for configuring the heating model
// *
// * (c) Dr. Stephen J. Bradshaw
// *
// * Source code generated by HYDRAD_GUI on 08-06-2018 17:56:27
// *
// ****

// **** Physics ****
// Heating //
#define HEATED_SPECIES 0
// End of Heating //
// Radiation //
#include "../../Radiation_Model/source/config.h"
// End of Radiation //
// **** End of Physics ****
