// ****
// *
// * #defines for configuring the heating model
// *
// * (c) Dr. Stephen J. Bradshaw
// *
// * Source code generated by HYDRAD_GUI on 28-11-2020 13:56:22
// *
// ****


// **** Physics ****
// Heating //
#define ELECTRON_HEATING_ONLY
#define ELECTRON_HEATING 1.0
// End of Heating //
// Radiation //
#include "../../Radiation_Model/source/config.h"
// End of Radiation //
// **** End of Physics ****
