// ****
// *
// * #defines for configuring the shortest collisional coupling timescale
// *
// * (c) Dr. Stephen J. Bradshaw
// *
// * Source code generated by HYDRAD_GUI on 08-06-2018 17:56:27
// *
// ****

// **** Physics ****
// Collisions //
#define MINIMUM_COLLISIONAL_COUPLING_TIME_SCALE 0.01
// End of Collisions //
// **** End of Physics ****
