// ****
// *
// * #defines for configuring the shortest collisional coupling timescale
// *
// * (c) Dr. Stephen J. Bradshaw
// *
// * Source code generated by HYDRAD_GUI on 03-11-2017 15:31:12
// *
// ****

// **** Physics ****
// Collisions //
#define MINIMUM_COLLISIONAL_COUPLING_TIME_SCALE 0.01
// End of Collisions //
// **** End of Physics ****
